// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = "DESKTOP";    // Network SSID (name)
const char PASS[]     = "ekamgaba";    // Network password (use for WPA, or use as key for WEP)

void onTempChange();

float temp;

void initProperties(){

  ArduinoCloud.addProperty(temp, READWRITE, ON_CHANGE, onTempChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
